apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::216989110867:role/eksctl-brain-tasks-cluster-nodegro-NodeInstanceRole-74jwYLdh2r6S
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::216989110867:role/CodeBuild-BrainTasks-service-Role
      username: codebuild
      groups:
        - system:masters
    - rolearn: arn:aws:iam::216989110867:role/service-role/AWSCodePipelineServiceRole-ap-south-1-Brain-Tasks-App-pipeline
      username: codepipeline
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-03T07:59:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "23344"
  uid: 26c09ed5-570b-4cf1-bc62-efa5f5f2b3b0
